local:
  name: https://github.com/igdianov/upstream
github:
  organisations:
  - name: igdianov
    repositories:
    - name: downstream
      # should be using default develop
      # branch: develop
